# Generated by Django 5.0.1 on 2024-02-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id_nota', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=12, verbose_name='Título')),
                ('contenido', models.CharField(max_length=10000, verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
